# Uncomment the next line to define a global platform for your project
platform :osx, '10.14'

target 'sparkleSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sparkleSample
  pod 'Sparkle'

  target 'sparkleSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sparkleSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
